### ISSUE TITLE
Gestion des urls

### ISSUE THREAD

**Issue by primael** [louis-genestier/php-image-proxy#1]
Lorsque je mets pour url shutterbox.com/car/car1.jpg il crée une nouvelle entrée. 
Idem pour shuTTerbox.com/car/car1.jpg
On ne devrait avoir qu'une seule entrée.

**Comment by louis-genestier** [comment]
Effectivement, j'ai ajouté la function strtolower à ma fonction qui me permettait d'obtenir l'url de l'image.
Merci
